### ISSUE TITLE
Change mappings for shapes GTFS file

### ISSUE THREAD

**Issue by marioscrock** [oeg-upm/gtfs-bench#96]
Mapping for shapes GTFS file can be improved generating for each unique `shape_id` a `gtfs:Shape` and several `gtfs:ShapePoint` for related rows.

**Comment by dachafra** [comment]
the mapping in YARRRML
```
shapes:
    sources:
      - [/home/magarcia/nextcloud/MV/grecia/shapes.txt~csv]
    s: http://transport.linkeddata.es/greece/shape/$(shape_id)
    po:
      - [a, gtfs:Shape]
      - [gtfs:shapePoint, http://transport.linkeddata.es/greece/shape_point/$(shape_id)-$(shape_pt_sequence)]
  shape_point:
    sources:
      - [/home/magarcia/nextcloud/MV/grecia/shapes.txt~csv]
    s: http://transport.linkeddata.es/greece/shape_point/$(shape_id)-$(shape_pt_sequence)
    po:
      - [a, gtfs:ShapePoint]
      - [geo:lat,$(shape_pt_lat),xsd:double]
      - [geo:long,$(shape_pt_lon),xsd:double]
      - [gtfs:pointSequence,$(shape_pt_sequence)]
      - [gtfs:distanceTraveled,$(shape_dist_traveled)]
```
